### ISSUE TITLE
Return an empty array for any empty many blocks

### ISSUE THREAD

**Issue by timriley** [icelab/formalist-standard-react#105]
_Copying @dylanwolff's issue from https://github.com/icelab/formalist/issues/56:_

<hr>

Given the following example `many` block:

```
many :left_masthead_menu_groups,
  label: "Left masthead menu groups",
  action_label: "Add a menu group",
  placeholder: "The left masthead doesn't have any menu groups yet." do
  select_box :menu_group_id,
    options: dep(:menu_groups_list),
    label: "Menu group"
end
```
When submitting the form with a value set in the `:menu_group_id` select box, the following attributes are posted:
```
{"left_masthead_menu_groups"=>[{"__rack_workaround"=>"", "menu_group_id"=>"2"}]}
```
However, when a value is not selected, `attributes` is `nil`. Ideally an empty array would be returned here.

**Comment by makenosound** [comment]
Closing as this isn’t actually the behaviour we want. Empty many blocks _should_ return an empty string from a form POST.
