### ISSUE TITLE
Implement front-end validation rules support

### ISSUE THREAD

**Issue by timriley** [icelab/formalist-standard-react#11]
Validation rules are now no longer extracted from the dry-validation schema, and are instead passed as a simple hash of rules/values on a `validation` attribute on `field` and `many` elements.

Now that the validations rules are 100% form-specific, we can build out a relatively complete standard set of rules. I think it'd be good to implement as many of the rules on https://github.com/dry-rb/dry-logic/blob/master/lib/dry/logic/predicates.rb as are practical in the front-end context.

**Comment by makenosound** [comment]
We’ve wrapped this up now using http://github.com/icelab/formalist-validation.
