### ISSUE TITLE
Clip long unbroken strings

### ISSUE THREAD

**Issue by makenosound** [icelab/formalist-standard-react#115]
https://trello.com/c/Q0mfSq24/195-long-url-in-embedded-code-is-causing-the-text-editing-box-to-extend-off-the-rhs-of-the-page

So that it doesn’t break the layout.

**Comment by dylanwolff** [comment]
Just mentioning this one again. I've today updated USSC to `v3.0.1` (via bumping `roneo` to `2.0.3`) and this is still an issue (see the example record mentioned in the Trello card linked above).

**Comment by makenosound** [comment]
@dylanwolff I’ve release v3.0.2 of `formalist-standard-react` which should fix this. We can bump explicitly in roneo if we need to (or you can probably adjust manually 🙄  in your `yarn.lock` file

**Comment by dylanwolff** [comment]
Great, thanks @makenosound. That has indeed fixed it. I've opted to manually modify the lockfile.

**Comment by makenosound** [comment]
Hurrah. Sorry it took a while!
