### ISSUE TITLE
Add tag-style "multi-select" field with AJAX-backed auto-complete

### ISSUE THREAD

**Issue by timriley** [icelab/formalist-standard-react#69]
It'd be great to add support for a field like this. An immediate use case would be for general tagging systems, so we could both use existing tags and create new ones on the fly.

**Comment by makenosound** [comment]
@timriley Yep, for sure. I think it should be a different type of field, since the interaction is pretty different.

**Comment by timriley** [comment]
Yes, I think this makes sense :) I wouldn't want to smoosh it into anything we already have!

**Comment by makenosound** [comment]
This is encompassed in the `search_selection_field` and the `search_multi_selection_field`s.
