### ISSUE TITLE
Setting search_threshold: 0 for a search_selection_field doesn't trigger a search when the control is mounted

### ISSUE THREAD

**Issue by dylanwolff** [icelab/formalist-standard-react#93]
An example from USSC:

![kapture 2016-11-24 at 7 24 10](https://cloud.githubusercontent.com/assets/10018241/20589056/13cfca52-b21a-11e6-8bc3-69d526f7d583.gif)

**Comment by makenosound** [comment]
@dylanwolff Ta, this should be resolved in https://github.com/icelab/formalist-standard-react/commit/5642fa294586793db8db0e69ad7ad13be4d00154
